from .api.parameters import delete_common_parameters_overriding_param as __delete_common_parameters_overriding_param
from .api.parameters import get_common_parameters_overriding_param as __get_common_parameters_overriding_param
from .api.parameters import get_same_name_multiple_locations_param as __get_same_name_multiple_locations_param
from .api.parameters import multiple_path_parameters as __multiple_path_parameters

get_common_parameters_overriding_param = __get_common_parameters_overriding_param.sync_detailed
get_common_parameters_overriding_param_async = __get_common_parameters_overriding_param.asyncio_detailed


delete_common_parameters_overriding_param = __delete_common_parameters_overriding_param.sync_detailed
delete_common_parameters_overriding_param_async = __delete_common_parameters_overriding_param.asyncio_detailed


get_same_name_multiple_locations_param = __get_same_name_multiple_locations_param.sync_detailed
get_same_name_multiple_locations_param_async = __get_same_name_multiple_locations_param.asyncio_detailed


multiple_path_parameters = __multiple_path_parameters.sync_detailed
multiple_path_parameters_async = __multiple_path_parameters.asyncio_detailed
