from .api.responses import post_responses_unions_simple_before_complex as __post_responses_unions_simple_before_complex

post_responses_unions_simple_before_complex = __post_responses_unions_simple_before_complex.sync
post_responses_unions_simple_before_complex_detailed = __post_responses_unions_simple_before_complex.sync_detailed
post_responses_unions_simple_before_complex_async = __post_responses_unions_simple_before_complex.asyncio
post_responses_unions_simple_before_complex_async_detailed = (
    __post_responses_unions_simple_before_complex.asyncio_detailed
)
