from .api.tests import callback_test as __callback_test
from .api.tests import defaults_tests_defaults_post as __defaults_tests_defaults_post
from .api.tests import description_with_backslash as __description_with_backslash
from .api.tests import get_basic_list_of_booleans as __get_basic_list_of_booleans
from .api.tests import get_basic_list_of_floats as __get_basic_list_of_floats
from .api.tests import get_basic_list_of_integers as __get_basic_list_of_integers
from .api.tests import get_basic_list_of_strings as __get_basic_list_of_strings
from .api.tests import get_user_list as __get_user_list
from .api.tests import int_enum_tests_int_enum_post as __int_enum_tests_int_enum_post
from .api.tests import json_body_tests_json_body_post as __json_body_tests_json_body_post
from .api.tests import no_response_tests_no_response_get as __no_response_tests_no_response_get
from .api.tests import octet_stream_tests_octet_stream_get as __octet_stream_tests_octet_stream_get
from .api.tests import post_form_data as __post_form_data
from .api.tests import post_form_data_inline as __post_form_data_inline
from .api.tests import post_tests_json_body_string as __post_tests_json_body_string
from .api.tests import test_inline_objects as __test_inline_objects
from .api.tests import token_with_cookie_auth_token_with_cookie_get as __token_with_cookie_auth_token_with_cookie_get
from .api.tests import (
    unsupported_content_tests_unsupported_content_get as __unsupported_content_tests_unsupported_content_get,
)
from .api.tests import upload_file_tests_upload_post as __upload_file_tests_upload_post
from .api.tests import upload_multiple_files_tests_upload_post as __upload_multiple_files_tests_upload_post

get_user_list = __get_user_list.sync
get_user_list_detailed = __get_user_list.sync_detailed
get_user_list_async = __get_user_list.asyncio
get_user_list_async_detailed = __get_user_list.asyncio_detailed


get_basic_list_of_strings = __get_basic_list_of_strings.sync
get_basic_list_of_strings_detailed = __get_basic_list_of_strings.sync_detailed
get_basic_list_of_strings_async = __get_basic_list_of_strings.asyncio
get_basic_list_of_strings_async_detailed = __get_basic_list_of_strings.asyncio_detailed


get_basic_list_of_integers = __get_basic_list_of_integers.sync
get_basic_list_of_integers_detailed = __get_basic_list_of_integers.sync_detailed
get_basic_list_of_integers_async = __get_basic_list_of_integers.asyncio
get_basic_list_of_integers_async_detailed = __get_basic_list_of_integers.asyncio_detailed


get_basic_list_of_floats = __get_basic_list_of_floats.sync
get_basic_list_of_floats_detailed = __get_basic_list_of_floats.sync_detailed
get_basic_list_of_floats_async = __get_basic_list_of_floats.asyncio
get_basic_list_of_floats_async_detailed = __get_basic_list_of_floats.asyncio_detailed


get_basic_list_of_booleans = __get_basic_list_of_booleans.sync
get_basic_list_of_booleans_detailed = __get_basic_list_of_booleans.sync_detailed
get_basic_list_of_booleans_async = __get_basic_list_of_booleans.asyncio
get_basic_list_of_booleans_async_detailed = __get_basic_list_of_booleans.asyncio_detailed


post_form_data = __post_form_data.sync_detailed
post_form_data_async = __post_form_data.asyncio_detailed


post_form_data_inline = __post_form_data_inline.sync_detailed
post_form_data_inline_async = __post_form_data_inline.asyncio_detailed


upload_file_tests_upload_post = __upload_file_tests_upload_post.sync
upload_file_tests_upload_post_detailed = __upload_file_tests_upload_post.sync_detailed
upload_file_tests_upload_post_async = __upload_file_tests_upload_post.asyncio
upload_file_tests_upload_post_async_detailed = __upload_file_tests_upload_post.asyncio_detailed


upload_multiple_files_tests_upload_post = __upload_multiple_files_tests_upload_post.sync
upload_multiple_files_tests_upload_post_detailed = __upload_multiple_files_tests_upload_post.sync_detailed
upload_multiple_files_tests_upload_post_async = __upload_multiple_files_tests_upload_post.asyncio
upload_multiple_files_tests_upload_post_async_detailed = __upload_multiple_files_tests_upload_post.asyncio_detailed


json_body_tests_json_body_post = __json_body_tests_json_body_post.sync
json_body_tests_json_body_post_detailed = __json_body_tests_json_body_post.sync_detailed
json_body_tests_json_body_post_async = __json_body_tests_json_body_post.asyncio
json_body_tests_json_body_post_async_detailed = __json_body_tests_json_body_post.asyncio_detailed


post_tests_json_body_string = __post_tests_json_body_string.sync
post_tests_json_body_string_detailed = __post_tests_json_body_string.sync_detailed
post_tests_json_body_string_async = __post_tests_json_body_string.asyncio
post_tests_json_body_string_async_detailed = __post_tests_json_body_string.asyncio_detailed


defaults_tests_defaults_post = __defaults_tests_defaults_post.sync
defaults_tests_defaults_post_detailed = __defaults_tests_defaults_post.sync_detailed
defaults_tests_defaults_post_async = __defaults_tests_defaults_post.asyncio
defaults_tests_defaults_post_async_detailed = __defaults_tests_defaults_post.asyncio_detailed


octet_stream_tests_octet_stream_get = __octet_stream_tests_octet_stream_get.sync
octet_stream_tests_octet_stream_get_detailed = __octet_stream_tests_octet_stream_get.sync_detailed
octet_stream_tests_octet_stream_get_async = __octet_stream_tests_octet_stream_get.asyncio
octet_stream_tests_octet_stream_get_async_detailed = __octet_stream_tests_octet_stream_get.asyncio_detailed


no_response_tests_no_response_get = __no_response_tests_no_response_get.sync_detailed
no_response_tests_no_response_get_async = __no_response_tests_no_response_get.asyncio_detailed


unsupported_content_tests_unsupported_content_get = __unsupported_content_tests_unsupported_content_get.sync_detailed
unsupported_content_tests_unsupported_content_get_async = (
    __unsupported_content_tests_unsupported_content_get.asyncio_detailed
)


int_enum_tests_int_enum_post = __int_enum_tests_int_enum_post.sync
int_enum_tests_int_enum_post_detailed = __int_enum_tests_int_enum_post.sync_detailed
int_enum_tests_int_enum_post_async = __int_enum_tests_int_enum_post.asyncio
int_enum_tests_int_enum_post_async_detailed = __int_enum_tests_int_enum_post.asyncio_detailed


test_inline_objects = __test_inline_objects.sync
test_inline_objects_detailed = __test_inline_objects.sync_detailed
test_inline_objects_async = __test_inline_objects.asyncio
test_inline_objects_async_detailed = __test_inline_objects.asyncio_detailed


token_with_cookie_auth_token_with_cookie_get = __token_with_cookie_auth_token_with_cookie_get.sync_detailed
token_with_cookie_auth_token_with_cookie_get_async = __token_with_cookie_auth_token_with_cookie_get.asyncio_detailed


callback_test = __callback_test.sync
callback_test_detailed = __callback_test.sync_detailed
callback_test_async = __callback_test.asyncio
callback_test_async_detailed = __callback_test.asyncio_detailed


description_with_backslash = __description_with_backslash.sync_detailed
description_with_backslash_async = __description_with_backslash.asyncio_detailed
